### ISSUE TITLE
Dotfiles/config files management

### ISSUE THREAD

**Issue by mecattaf** [Heus-Sueh/ublue-images#3]
Hi there, great work on ublue-images

How do you manage your config files? Say you want to update your sway config, how are these changes reflected in this repo?

**Comment by Heus-Sueh** [comment]
> Hi there, great work on ublue-images
> 
> How do you manage your config files? Say you want to update your sway config, how are these changes reflected in this repo?

Currently, I am managing the dotfiles directly in the image directory `etc/skel` which you can find in the `hyprland` and `swayfx` files, for now I only know about this "easier" method, I opened a discussion about dotfiles in the ublue discourse and people gave more ideas on how to deal with dotfiles

https://universal-blue.discourse.group/t/dotfiles-and-custom-images/596

**Comment by mecattaf** [comment]
Thanks, will follow this thread!
